units: AH4_input.tsv
species: horse
ref: goldenPath
bucket: results
sif: unicorn.sif
ref_fasta: /home/refgen/horse/goldenPath/goldenPath.Ec_build-3.0_wMSY.fa
known_sites:
  dbsnp_snp_vcf: /home/refgen/horse/goldenPath/resources/equus_caballus.chrIDmod.vcf.gz
  mnec2m_snp_vcf: /home/refgen/horse/goldenPath/resources/MNEc2M.EquCab3.09182018.recode.rmGT.refseqnames.chrIDmod.vcf.gz
